// Code generated by ent, DO NOT EDIT.

package ent

import (
	"anheyu-app/ent/link"
	"anheyu-app/ent/linkcategory"
	"anheyu-app/ent/linktag"
	"anheyu-app/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LinkUpdate is the builder for updating Link entities.
type LinkUpdate struct {
	config
	hooks     []Hook
	mutation  *LinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LinkUpdate builder.
func (lu *LinkUpdate) Where(ps ...predicate.Link) *LinkUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetName sets the "name" field.
func (lu *LinkUpdate) SetName(s string) *LinkUpdate {
	lu.mutation.SetName(s)
	return lu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableName(s *string) *LinkUpdate {
	if s != nil {
		lu.SetName(*s)
	}
	return lu
}

// SetURL sets the "url" field.
func (lu *LinkUpdate) SetURL(s string) *LinkUpdate {
	lu.mutation.SetURL(s)
	return lu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableURL(s *string) *LinkUpdate {
	if s != nil {
		lu.SetURL(*s)
	}
	return lu
}

// SetLogo sets the "logo" field.
func (lu *LinkUpdate) SetLogo(s string) *LinkUpdate {
	lu.mutation.SetLogo(s)
	return lu
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableLogo(s *string) *LinkUpdate {
	if s != nil {
		lu.SetLogo(*s)
	}
	return lu
}

// ClearLogo clears the value of the "logo" field.
func (lu *LinkUpdate) ClearLogo() *LinkUpdate {
	lu.mutation.ClearLogo()
	return lu
}

// SetDescription sets the "description" field.
func (lu *LinkUpdate) SetDescription(s string) *LinkUpdate {
	lu.mutation.SetDescription(s)
	return lu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableDescription(s *string) *LinkUpdate {
	if s != nil {
		lu.SetDescription(*s)
	}
	return lu
}

// ClearDescription clears the value of the "description" field.
func (lu *LinkUpdate) ClearDescription() *LinkUpdate {
	lu.mutation.ClearDescription()
	return lu
}

// SetStatus sets the "status" field.
func (lu *LinkUpdate) SetStatus(l link.Status) *LinkUpdate {
	lu.mutation.SetStatus(l)
	return lu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableStatus(l *link.Status) *LinkUpdate {
	if l != nil {
		lu.SetStatus(*l)
	}
	return lu
}

// SetSiteshot sets the "siteshot" field.
func (lu *LinkUpdate) SetSiteshot(s string) *LinkUpdate {
	lu.mutation.SetSiteshot(s)
	return lu
}

// SetNillableSiteshot sets the "siteshot" field if the given value is not nil.
func (lu *LinkUpdate) SetNillableSiteshot(s *string) *LinkUpdate {
	if s != nil {
		lu.SetSiteshot(*s)
	}
	return lu
}

// ClearSiteshot clears the value of the "siteshot" field.
func (lu *LinkUpdate) ClearSiteshot() *LinkUpdate {
	lu.mutation.ClearSiteshot()
	return lu
}

// SetCategoryID sets the "category" edge to the LinkCategory entity by ID.
func (lu *LinkUpdate) SetCategoryID(id int) *LinkUpdate {
	lu.mutation.SetCategoryID(id)
	return lu
}

// SetCategory sets the "category" edge to the LinkCategory entity.
func (lu *LinkUpdate) SetCategory(l *LinkCategory) *LinkUpdate {
	return lu.SetCategoryID(l.ID)
}

// AddTagIDs adds the "tags" edge to the LinkTag entity by IDs.
func (lu *LinkUpdate) AddTagIDs(ids ...int) *LinkUpdate {
	lu.mutation.AddTagIDs(ids...)
	return lu
}

// AddTags adds the "tags" edges to the LinkTag entity.
func (lu *LinkUpdate) AddTags(l ...*LinkTag) *LinkUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return lu.AddTagIDs(ids...)
}

// Mutation returns the LinkMutation object of the builder.
func (lu *LinkUpdate) Mutation() *LinkMutation {
	return lu.mutation
}

// ClearCategory clears the "category" edge to the LinkCategory entity.
func (lu *LinkUpdate) ClearCategory() *LinkUpdate {
	lu.mutation.ClearCategory()
	return lu
}

// ClearTags clears all "tags" edges to the LinkTag entity.
func (lu *LinkUpdate) ClearTags() *LinkUpdate {
	lu.mutation.ClearTags()
	return lu
}

// RemoveTagIDs removes the "tags" edge to LinkTag entities by IDs.
func (lu *LinkUpdate) RemoveTagIDs(ids ...int) *LinkUpdate {
	lu.mutation.RemoveTagIDs(ids...)
	return lu
}

// RemoveTags removes "tags" edges to LinkTag entities.
func (lu *LinkUpdate) RemoveTags(l ...*LinkTag) *LinkUpdate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return lu.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LinkUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LinkUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LinkUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LinkUpdate) check() error {
	if v, ok := lu.mutation.Name(); ok {
		if err := link.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Link.name": %w`, err)}
		}
	}
	if v, ok := lu.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	if v, ok := lu.mutation.Status(); ok {
		if err := link.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Link.status": %w`, err)}
		}
	}
	if lu.mutation.CategoryCleared() && len(lu.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Link.category"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (lu *LinkUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LinkUpdate {
	lu.modifiers = append(lu.modifiers, modifiers...)
	return lu
}

func (lu *LinkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Name(); ok {
		_spec.SetField(link.FieldName, field.TypeString, value)
	}
	if value, ok := lu.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
	}
	if value, ok := lu.mutation.Logo(); ok {
		_spec.SetField(link.FieldLogo, field.TypeString, value)
	}
	if lu.mutation.LogoCleared() {
		_spec.ClearField(link.FieldLogo, field.TypeString)
	}
	if value, ok := lu.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
	}
	if lu.mutation.DescriptionCleared() {
		_spec.ClearField(link.FieldDescription, field.TypeString)
	}
	if value, ok := lu.mutation.Status(); ok {
		_spec.SetField(link.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := lu.mutation.Siteshot(); ok {
		_spec.SetField(link.FieldSiteshot, field.TypeString, value)
	}
	if lu.mutation.SiteshotCleared() {
		_spec.ClearField(link.FieldSiteshot, field.TypeString)
	}
	if lu.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if lu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   link.TagsTable,
			Columns: link.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linktag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.RemovedTagsIDs(); len(nodes) > 0 && !lu.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   link.TagsTable,
			Columns: link.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linktag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   link.TagsTable,
			Columns: link.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linktag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(lu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LinkUpdateOne is the builder for updating a single Link entity.
type LinkUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LinkMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (luo *LinkUpdateOne) SetName(s string) *LinkUpdateOne {
	luo.mutation.SetName(s)
	return luo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableName(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetName(*s)
	}
	return luo
}

// SetURL sets the "url" field.
func (luo *LinkUpdateOne) SetURL(s string) *LinkUpdateOne {
	luo.mutation.SetURL(s)
	return luo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableURL(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetURL(*s)
	}
	return luo
}

// SetLogo sets the "logo" field.
func (luo *LinkUpdateOne) SetLogo(s string) *LinkUpdateOne {
	luo.mutation.SetLogo(s)
	return luo
}

// SetNillableLogo sets the "logo" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableLogo(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetLogo(*s)
	}
	return luo
}

// ClearLogo clears the value of the "logo" field.
func (luo *LinkUpdateOne) ClearLogo() *LinkUpdateOne {
	luo.mutation.ClearLogo()
	return luo
}

// SetDescription sets the "description" field.
func (luo *LinkUpdateOne) SetDescription(s string) *LinkUpdateOne {
	luo.mutation.SetDescription(s)
	return luo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableDescription(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetDescription(*s)
	}
	return luo
}

// ClearDescription clears the value of the "description" field.
func (luo *LinkUpdateOne) ClearDescription() *LinkUpdateOne {
	luo.mutation.ClearDescription()
	return luo
}

// SetStatus sets the "status" field.
func (luo *LinkUpdateOne) SetStatus(l link.Status) *LinkUpdateOne {
	luo.mutation.SetStatus(l)
	return luo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableStatus(l *link.Status) *LinkUpdateOne {
	if l != nil {
		luo.SetStatus(*l)
	}
	return luo
}

// SetSiteshot sets the "siteshot" field.
func (luo *LinkUpdateOne) SetSiteshot(s string) *LinkUpdateOne {
	luo.mutation.SetSiteshot(s)
	return luo
}

// SetNillableSiteshot sets the "siteshot" field if the given value is not nil.
func (luo *LinkUpdateOne) SetNillableSiteshot(s *string) *LinkUpdateOne {
	if s != nil {
		luo.SetSiteshot(*s)
	}
	return luo
}

// ClearSiteshot clears the value of the "siteshot" field.
func (luo *LinkUpdateOne) ClearSiteshot() *LinkUpdateOne {
	luo.mutation.ClearSiteshot()
	return luo
}

// SetCategoryID sets the "category" edge to the LinkCategory entity by ID.
func (luo *LinkUpdateOne) SetCategoryID(id int) *LinkUpdateOne {
	luo.mutation.SetCategoryID(id)
	return luo
}

// SetCategory sets the "category" edge to the LinkCategory entity.
func (luo *LinkUpdateOne) SetCategory(l *LinkCategory) *LinkUpdateOne {
	return luo.SetCategoryID(l.ID)
}

// AddTagIDs adds the "tags" edge to the LinkTag entity by IDs.
func (luo *LinkUpdateOne) AddTagIDs(ids ...int) *LinkUpdateOne {
	luo.mutation.AddTagIDs(ids...)
	return luo
}

// AddTags adds the "tags" edges to the LinkTag entity.
func (luo *LinkUpdateOne) AddTags(l ...*LinkTag) *LinkUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return luo.AddTagIDs(ids...)
}

// Mutation returns the LinkMutation object of the builder.
func (luo *LinkUpdateOne) Mutation() *LinkMutation {
	return luo.mutation
}

// ClearCategory clears the "category" edge to the LinkCategory entity.
func (luo *LinkUpdateOne) ClearCategory() *LinkUpdateOne {
	luo.mutation.ClearCategory()
	return luo
}

// ClearTags clears all "tags" edges to the LinkTag entity.
func (luo *LinkUpdateOne) ClearTags() *LinkUpdateOne {
	luo.mutation.ClearTags()
	return luo
}

// RemoveTagIDs removes the "tags" edge to LinkTag entities by IDs.
func (luo *LinkUpdateOne) RemoveTagIDs(ids ...int) *LinkUpdateOne {
	luo.mutation.RemoveTagIDs(ids...)
	return luo
}

// RemoveTags removes "tags" edges to LinkTag entities.
func (luo *LinkUpdateOne) RemoveTags(l ...*LinkTag) *LinkUpdateOne {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return luo.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the LinkUpdate builder.
func (luo *LinkUpdateOne) Where(ps ...predicate.Link) *LinkUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LinkUpdateOne) Select(field string, fields ...string) *LinkUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Link entity.
func (luo *LinkUpdateOne) Save(ctx context.Context) (*Link, error) {
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LinkUpdateOne) SaveX(ctx context.Context) *Link {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LinkUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LinkUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LinkUpdateOne) check() error {
	if v, ok := luo.mutation.Name(); ok {
		if err := link.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Link.name": %w`, err)}
		}
	}
	if v, ok := luo.mutation.URL(); ok {
		if err := link.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Link.url": %w`, err)}
		}
	}
	if v, ok := luo.mutation.Status(); ok {
		if err := link.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Link.status": %w`, err)}
		}
	}
	if luo.mutation.CategoryCleared() && len(luo.mutation.CategoryIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Link.category"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (luo *LinkUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LinkUpdateOne {
	luo.modifiers = append(luo.modifiers, modifiers...)
	return luo
}

func (luo *LinkUpdateOne) sqlSave(ctx context.Context) (_node *Link, err error) {
	if err := luo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(link.Table, link.Columns, sqlgraph.NewFieldSpec(link.FieldID, field.TypeInt))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Link.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, link.FieldID)
		for _, f := range fields {
			if !link.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != link.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Name(); ok {
		_spec.SetField(link.FieldName, field.TypeString, value)
	}
	if value, ok := luo.mutation.URL(); ok {
		_spec.SetField(link.FieldURL, field.TypeString, value)
	}
	if value, ok := luo.mutation.Logo(); ok {
		_spec.SetField(link.FieldLogo, field.TypeString, value)
	}
	if luo.mutation.LogoCleared() {
		_spec.ClearField(link.FieldLogo, field.TypeString)
	}
	if value, ok := luo.mutation.Description(); ok {
		_spec.SetField(link.FieldDescription, field.TypeString, value)
	}
	if luo.mutation.DescriptionCleared() {
		_spec.ClearField(link.FieldDescription, field.TypeString)
	}
	if value, ok := luo.mutation.Status(); ok {
		_spec.SetField(link.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := luo.mutation.Siteshot(); ok {
		_spec.SetField(link.FieldSiteshot, field.TypeString, value)
	}
	if luo.mutation.SiteshotCleared() {
		_spec.ClearField(link.FieldSiteshot, field.TypeString)
	}
	if luo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   link.CategoryTable,
			Columns: []string{link.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linkcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if luo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   link.TagsTable,
			Columns: link.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linktag.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.RemovedTagsIDs(); len(nodes) > 0 && !luo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   link.TagsTable,
			Columns: link.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linktag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   link.TagsTable,
			Columns: link.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(linktag.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(luo.modifiers...)
	_node = &Link{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{link.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
